Add failing test case for #28
Sometimes it does work, results are inconsistent:

	$ go run -count=10
	--- FAIL: TestArrayIgnore (0.00s)
	formam_test.go:923:
		out:  [{a@a.a}]
		want: [{a@a.a} {b@b.b}]
	--- FAIL: TestArrayIgnore (0.00s)
	formam_test.go:923:
		out:  [{a@a.a}]
		want: [{a@a.a} {b@b.b}]
	--- FAIL: TestArrayIgnore (0.00s)
	formam_test.go:923:
		out:  [{a@a.a}]
		want: [{a@a.a} {b@b.b}]
	--- FAIL: TestArrayIgnore (0.00s)
	formam_test.go:923:
		out:  [{a@a.a}]
		want: [{a@a.a} {b@b.b}]
	--- FAIL: TestArrayIgnore (0.00s)
	formam_test.go:923:
		out:  [{a@a.a}]
		want: [{a@a.a} {b@b.b}]
	--- FAIL: TestArrayIgnore (0.00s)
	formam_test.go:923:
		out:  [{a@a.a}]
		want: [{a@a.a} {b@b.b}]
	--- FAIL: TestArrayIgnore (0.00s)
	formam_test.go:923:
		out:  [{a@a.a}]
		want: [{a@a.a} {b@b.b}]
	--- FAIL: TestArrayIgnore (0.00s)
	formam_test.go:923:
		out:  [{a@a.a}]
		want: [{a@a.a} {b@b.b}]

Only failed 8 times, instead of 10.

Didn't look at the isue, but guess it's a map order thing?